---
- name: gathering vm configuration
  delegate_to: "{{ pve_target_node }}"
  inett.pve.vm_get_config:
    vmid: "{{ pve_vmid }}"
  register: _pve_vm_get_config
  when:
    - pve_vm_state != 'absent'
  tags: ["always"]

- name: resize disks
  vars:
    c_key: "scsi{{ item.key }}"
  delegate_to: "{{ pve_target_node }}"
  inett.pve.vm_disk_resize:
    vmid: "{{ pve_vmid }}"
    disk: "{{ c_key }}"
    size: "{{ item.value['size'] }}"
  when:
    - pve_vm_state != 'absent'
    - "c_key in _pve_vm_get_config.pve_vm_config[1]"
    - "'size' in item.value"
  with_dict: "{{ pve_vm_scsi }}"
  tags: ["always"]

- name: create disks
  vars:
    c_key: "scsi{{ item.key }}"
  delegate_to: "{{ pve_target_node }}"
  inett.pve.vm_disks:
    vmid: "{{ pve_vmid }}"
    scsi: "{ {{item.key}}: {{item.value}} }"
    storage: "{{ pve_vm_storage }}"
  when:
    - pve_vm_state != 'absent'
    - c_key not in _pve_vm_get_config.pve_vm_config[1]
  with_dict: "{{ pve_vm_scsi }}"
  tags: ["always"]

