- name: Generate pvereport on the nodes and fetch it back
  hosts: pve_nodes
  become: true
  become_user: root
  tasks:
    - name: Generate pvereport on node
      ansible.builtin.shell: pvereport >> /pvereport
    - name: Fetch pvereport from node
      ansible.builtin.fetch:
        src: /pvereport
        dest: ../pvereport
    - name: Remove pvereport from node
      ansible.builtin.file:
        path: /pvereport
        state: absent
