---
- hosts: pve_nodes
  gather_facts: False
  roles:
    - inett.pve.cluster_group
  tags: always

- hosts: pve_vms
  gather_facts: False
  roles:
    - inett.pve.vm_prepare_facts
  tags: always

- hosts: pve_vms
  gather_facts: False
  roles:
    - inett.pve.vms
    - inett.pve.vms_finish
